export const filters = [
    {key: "1977", value: "contrast(1.1) brightness(1.1) saturate(1.1)"},
    {key: "aden", value: "contrast(0.9) brightness(1.2) hue-rotate(-20deg) saturate(0.85)"},
    {key: "amaro", value: "contrast(0.9) brightness(1.1) hue-rotate(-10deg) saturate(1.5)"},
    {key: "brannan", value: "contrast(1.4) sepia(0.5)"},
    {key: "clarendon", value: "contrast(1.2) saturate(1.35)"},
    {key: "earlyBird", value: "contrast(0.9) sepia(0.2)"},
    {key: "gingham", value: "brightness(1.05) hue-rotate(-10deg)"},
    {key: "hudson", value: "contrast(0.9) brightness(1.2) saturate(1.1)"},
    {key: "inkwell", value: "sepia(0.3) contrast(1.1) brightness(1.1) grayscale(1)"},
    {key: "kelvin", value: ":after { background: #b77d21 } :before: {background: #382c34}"},
    {key: "lark", value: "contrast(0.9)"},
    {key: "lofi", value: "contrast(1.5) saturate(1.1)"},
    {key: "maven", value: "contrast(0.95) brightness(0.95) saturate(1.5) sepia(0.25)"},
    {key: "mayfair", value: "contrast(1.1) saturate(1.1)"},
    {key: "moon", value: "contrast(1.1) brightness(1.1) grayscale(1)"},
    {key: "perpetua", value: ""},
    {key: "reyes", value: "contrast(0.85) brightness(1.1) saturate(0.75) sepia(0.22)"},
    {key: "rise", value: "contrast(0.9) brightness(1.05) saturate(0.9) sepia(0.2)"},
    {key: "slumber", value: "saturate(0.66) brightness(1.05)"},
    {key: "stinson", value: "contrast(0.75) brightness(1.15) saturate(0.85)"},
    {key: "toaster", value: "contrast(1.5) brightness(0.9)"},
    {key: "valencia", value: "contrast(1.08) brightness(1.08) sepia(0.08)"},
    {key: "walden", value: "brightness(1.1) hue-rotate(-10deg) sepia(0.3) saturate(1.6)"},
    {key: "willow", value: "contrast(0.95) brightness(0.9) grayscale(0.5)"},
    {key: "xpro", value: "sepia(0.3)"} 
];

